apps/dashboards/urls.py
from django.conf.urls import patterns, url
from django.views.generic.simple import redirect_to


urlpatterns = patterns('dashboards.views',
    url(r'^dashboards/revisions$', 'revisions', name='dashboards.revisions'),
    url(r'^dashboards/user_lookup$', 'user_lookup',
        name='dashboards.user_lookup'),
    url(r'^dashboards/topic_lookup$', 'topic_lookup',
        name='dashboards.topic_lookup'),

    url(r'^dashboards/localization$', redirect_to,
        {'url': '/docs/MDN/Doc_status/Overview'}),
)

urls.py
from django.conf.urls import include, patterns, url
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.shortcuts import redirect, render
from django.views.i18n import javascript_catalog
from django.views.decorators.cache import cache_page

import badger


admin.autodiscover()
badger.autodiscover()


# Handle 404 and 500 errors
def _error_page(request, status):
    """Render error pages with jinja2."""
    return render(request, '%d.html' % status, status=status)
handler403 = lambda r: _error_page(r, 403)
handler404 = lambda r: _error_page(r, 404)
handler500 = lambda r: _error_page(r, 500)

urlpatterns = patterns('',
   # Home / landing pages:
    ('', include('landing.urls')),
    ('', include('devmo.urls')),
    (r'^demos/', include('demos.urls')),
    (r'^demos', lambda x: redirect('demos')),

    # Django admin:
    (r'^grappelli/', include('grappelli.urls')),
    (r'^admin/', include('smuggler.urls')),
    (r'^admin/', include(admin.site.urls)),

    (r'^search', include('search.urls')),

    (r'^docs', include('wiki.urls')),

    # Javascript translations.
    url(r'^jsi18n/.*$', cache_page(60 * 60 * 24 * 365)(javascript_catalog),
        {'domain': 'javascript', 'packages': [settings.ROOT_PACKAGE]},
        name='jsi18n'),

    url(r'^', include('dashboards.urls')),

    # Files.
    url(r'^files/new/$',
        'wiki.views.new_attachment',
        name='wiki.new_attachment'),
    url(r'^files/(?P<attachment_id>\d+)/$',
        'wiki.views.attachment_detail',
        name='wiki.attachment_detail'),
    url(r'^files/(?P<attachment_id>\d+)/edit/$',
        'wiki.views.edit_attachment',
        name='wiki.edit_attachment'),
    url(r'^files/(?P<attachment_id>\d+)/history/$',
        'wiki.views.attachment_history',
        name='wiki.attachment_history'),
    url(r'^files/(?P<attachment_id>\d+)/(?P<filename>.+)$',
        'wiki.views.raw_file',
        name='wiki.raw_file'),

    # Users
    ('', include('users.urls')),

    # BrowserID Realm
    url(r'^\.well-known/browserid-realm', 'users.views.browserid_realm',
        name='users.browserid-realm'),

    # Auth keys
    (r'^keys/', include('authkeys.urls')),

    # Badges
    (r'^badges/', include('badger.urls_simple')),

    # Services and sundry.
    (r'^', include('tidings.urls')),
    (r'^humans.txt$', 'django.views.static.serve',
        {'document_root': settings.HUMANSTXT_ROOT, 'path': 'humans.txt'}),

    url(r'^miel$', handler500, name='users.honeypot'),
)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

if settings.SERVE_MEDIA:
    media_url = settings.MEDIA_URL.lstrip('/').rstrip('/')
    urlpatterns += patterns('',
        (r'^%s/(?P<path>.*)$' % media_url, 'django.views.static.serve',
          {'document_root': settings.MEDIA_ROOT}),
    )

# Legacy MindTouch redirects. These go last so that they don't mess
# with local instances' ability to serve media.
urlpatterns += patterns('',
                        url(r'^@api/deki/files/(?P<file_id>\d+)/=(?P<filename>.+)$',
                            'wiki.views.mindtouch_file_redirect',
                            name='wiki.mindtouch_file_redirect'),
                        (r'^(?P<path>.*)$', 'wiki.views.mindtouch_to_kuma_redirect'),
)

apps/dashboards/models.py
# models.py

apps/dashboards/forms.py
from django import forms
from sumo.form_fields import StrippedCharField

from django.conf import settings

from tower import ugettext_lazy as _lazy
from tower import ugettext as _

LANG_CHOICES = [('', _lazy('All Locales'))] + settings.LANGUAGES


class RevisionDashboardForm(forms.Form):

    locale = forms.ChoiceField(choices=LANG_CHOICES,
                    # Required for non-translations, which is
                    # enforced in Document.clean().
                    required=False,
                    label=_lazy(u'Locale:'))

    user = StrippedCharField(min_length=1, max_length=255,
                    required=False,
                    label=_lazy(u'User:'))

    topic = StrippedCharField(min_length=1, max_length=255,
                    required=False,
                    label=_lazy(u'Topic:'))

    start_date = forms.DateField(required=False, label=_lazy(u'Start Date:'),
                    input_formats=settings.DATE_INPUT_FORMATS,
                    widget=forms.TextInput(attrs={'pattern': '\d{1,2}/\d{1,2}/\d{4}'}))

    end_date = forms.DateField(required=False, label=_lazy(u'End Date:'),
                    input_formats=settings.DATE_INPUT_FORMATS,
                    widget=forms.TextInput(attrs={'pattern': '\d{1,2}/\d{1,2}/\d{4}'}))

apps/dashboards/views.py
import json
import datetime

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render
from django.views.decorators.http import require_GET

from jinja2 import escape

from sumo.urlresolvers import reverse
from sumo.utils import paginate, smart_int

from users.helpers import ban_link

from wiki.models import Document, Revision
from wiki.helpers import format_comment

from dashboards.forms import RevisionDashboardForm

from . import PAGE_SIZE


@require_GET
def revisions(request):
    """Dashboard for reviewing revisions"""

    filter_form = RevisionDashboardForm(request.GET)
    page = request.GET.get('page', 1)

    revisions = (Revision.objects.select_related('creator')
                        .order_by('-created')
                        .defer('content'))

    query_kwargs = False

    # We can validate right away because no field is required
    if filter_form.is_valid():
        query_kwargs = {}
        query_kwargs_map = {
            'user': 'creator__username__istartswith',
            'locale': 'document__locale',
            'topic': 'slug__icontains',
        }

        # Build up a dict of the filter conditions, if any, then apply
        # them all in one go.
        for fieldname, kwarg in query_kwargs_map.items():
            filter_arg = filter_form.cleaned_data[fieldname]
            if filter_arg:
                query_kwargs[kwarg] = filter_arg

        start_date = filter_form.cleaned_data['start_date']
        if start_date:
            end_date = (filter_form.cleaned_data['end_date'] or
                                datetime.datetime.now())
            query_kwargs['created__range'] = [start_date, end_date]

    if query_kwargs:
        revisions = revisions.filter(**query_kwargs)
        total = revisions.count()
    else:
        # If no filters, just do a straight count(). It's the same
        # result, but much faster to compute.
        total = Revision.objects.count()

    # Only bother with this if we're actually going to get
    # some revisions from it. Otherwise it's a pointless but
    # potentially complex query.
    revisions = paginate(request, revisions, per_page=PAGE_SIZE)

    context = {'revisions': revisions, 'page': page, 'total': total}

    # Serve the response HTML conditionally upon reques type
    if request.is_ajax():
        return render(request,
            'dashboards/includes/revision_dashboard_body.html',
            context)
    else:
        context['form'] = filter_form

    return render(request, 'dashboards/revisions.html', context)


@require_GET
def user_lookup(request):
    """Returns partial username matches"""
    userlist = []

    if request.is_ajax():
        user = request.GET.get('user', '')
        if user:
            matches = User.objects.filter(username__istartswith=user)
            for u in matches:
                userlist.append({'label': u.username})

    data = json.dumps(userlist)
    return HttpResponse(data,
                        content_type='application/json; charset=utf-8')


@require_GET
def topic_lookup(request):
    """Returns partial topic matches"""
    topiclist = []

    if request.is_ajax():
        topic = request.GET.get('topic', '')
        if topic:
            matches = Document.objects.filter(slug__icontains=topic)
            for d in matches:
                topiclist.append({'label': d.slug})

    data = json.dumps(topiclist)
    return HttpResponse(data,
                        content_type='application/json; charset=utf-8')

apps/dashboards/templates/dashboards/revisions.html
{% extends "base.html" %}
{% set title = _('Revision Dashboard') %}
{% set styles = ('dashboards', 'jquery-ui') %}
{% set classes = 'compare' %}

{% block title %}{{ page_title(title) }}{% endblock %}

{% block content %}

    <div class="dashboard">

        <h1>{{ title }}</h1>
        <form method="get" id="revision-filter">
            <div class="revision-field">
                <label for="id_locale">{{ _('Locale:') }}</label>
                {{ form.locale }}
            </div>

            <div class="revision-field">
                <label for="id_user">{{ _('User:') }}</label>
                {{ form.user }}
            </div>

            <div class="revision-field">
                <label for="id_topic">{{ _('Topic:') }}</label>
                {{ form.topic }}
            </div>
            <br />

            <div class="revision-field">
                <label for="id_start_date">{{ _('Start Date:') }}</label>
                {{ form.start_date }}
            </div>

            <div class="revision-field">
                <label for="id_end_date">{{ _('End Date:') }}</label>
                {{ form.end_date }}
            </div>

            <button type="submit">{{ _('Filter') }}</button>
            <input type="hidden" name="page" id="revision-page" value="{{ page }}" />
        </form>


        <div id="revision-replace-block">
        {% include 'dashboards/includes/revision_dashboard_body.html' %}
        </div>
    </div>

{% endblock %}


{% block js %}
{{ js('jquery-ui') }}

<script>
(function (jQuery) {
    'use strict';

    var $revisionReplaceBlock = $('#revision-replace-block');
    var $localeInput = $('#id_locale');
    var $filterForm = $('#revision-filter');
    var $pageInput = $('#revision-page');
    var currentLocale = '{{ request.locale }}';

    var controlsTemplate = '\
    <div class="action-bar">\
        <ul id="page-buttons">\
            <li><a id="revert" href="$reverturl" class="button">{{ _('Revert') }}<i aria-hidden="true" class="icon-undo"></i></a></li><li><a id="view" href="$viewurl" class="button">{{ _('View Page') }}<i aria-hidden="true" class="icon-circle-arrow-right"></i></a></li><li class="page-edit"><a id="edit" href="$editurl" class="button">{{ _('Edit Page') }}<i aria-hidden="true" class="icon-pencil"></i></a></li><li class="page-history"><a id="history" href="$historyurl" class="button">{{ _('History') }}<i aria-hidden="true" class="icon-book"></i></a></li>\
        </ul>\
    </div>';

    // Create the autocomplete for user
    $('#id_user').mozillaAutocomplete({
        minLength: 3,
        labelField: 'label',
        autocompleteUrl: '{{ url("dashboards.user_lookup") }}',
        buildRequestData: function (req) {
            // Should add locale value here
            req.locale = getLocale();
            req.user = req.term;
            return req;
        }
    });

    // Create the autocomplete for topic
    $('#id_topic').mozillaAutocomplete({
        minLength: 3,
        labelField: 'label',
        autocompleteUrl: '{{ url("dashboards.topic_lookup") }}',
        buildRequestData: function (req) {
            // Should add locale value here
            req.locale = getLocale();
            req.topic = req.term;
            return req;
        }
    });

    // Enable keynav
    $revisionReplaceBlock.mozKeyboardNav({
        itemSelector: '.dashboard-row',
        onEnterKey: function (item) {
            $(item).trigger('mdn:click');
        },
        alwaysCollectItems: true
    });

    // Focus on the first item, if there
    focusFirst();

    // Create date pickers
    $('#id_start_date, #id_end_date').datepicker();

    // When an item is clicked, load its detail
    $revisionReplaceBlock.on('click mdn:click', '.dashboard-row', function (e) {
        var $this = $(this);
        var $detail;

        // Don't interrupt links and stop if a request is already running
        if (e.target.tagName == 'A' || $this.attr('data-running')) return;

        if ($this.attr('data-loaded')) {
            $this.find('.dashboard-detail').slideToggle();
        } else {
            $this.attr('data-running', 1);
            $.ajax({
                url: $this.attr('data-compare-url')
            }).then(function (content) {
                // Prepend the controls
                var controls = controlsTemplate
                                        .replace('$reverturl', $this.attr('data-revert-url'))
                                        .replace('$viewurl', $this.attr('data-view-url'))
                                        .replace('$editurl', $this.attr('data-edit-url'))
                                        .replace('$historyurl', $this.attr('data-history-url'));

                $detail = $('<div class="dashboard-detail">' + controls + content + '</div>').appendTo($this).slideDown();
                $this.attr('data-loaded', 1);
                $this.removeAttr('data-running');
            });
        }
    });

    // AJAX loads for pagination
    $revisionReplaceBlock.on('click', '.pagination a', function (e) {
        e.preventDefault();
        $pageInput.val(this.href.split('page=')[1]);
        $filterForm.submit();
    });

    // Filter form submission handler; loads content via AJAX, updates URL state
    $filterForm.on('submit', function (e) {
        e.preventDefault();
        var $this = $(this);

        if ('pushState' in history) {
            history.pushState(null, '', location.pathname + '?' + $this.serialize());
        }

        $.ajax({
            url: $this.attr('action'),
            data: $this.serialize()
        }).then(function (content) {
            replaceContent(content);
            $this.trigger('ajaxComplete');

            // Reset the page count to 0 in case of new filter
            $pageInput.val(1);
        });
    });

    // Returns the current locale
    function getLocale() {
        return $localeInput.get(0).value || currentLocale;
    }

    // Focuses on the first row in the table
    function focusFirst() {
        var first = $revisionReplaceBlock.find('.dashboard-row').first();
        first.length && first.get(0).focus();
    }

    // Replaces table body content and scrolls to top of the page
    function replaceContent(content) {
        $revisionReplaceBlock.fadeOut(function () {
            $(this).html(content).fadeIn(function () {
                focusFirst();
            });

            // Animate to top!
            $('html, body').animate({
                scrollTop: $revisionReplaceBlock.offset().top
            }, 2000);
        });
    }

})(jQuery);
</script>
{% endblock %}